version: '3'

networks:
  default:
    external:
      name: caddy_net

services:
  postgres:
    image: postgres:10
    container_name: invidious-db
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./init/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: $postgres_password
      POSTGRES_USER: $postgres_user
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  invidious:
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile
    image: omarroth/invidious
    container_name: invidious-app
    restart: unless-stopped
    environment:
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 4
        check_tables: true
        feed_threads: 4
        db:
          user: $invidious_db_user
          password: $invidious_db_password
          host: postgres
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: false
        domain:
    depends_on:
      - postgres

volumes:
  postgresdata:
