version: "3"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - ./data:/downloads
    ports:
      - 9117:9117
    restart: always
