version: "2.4"

networks:
  default:
    external: 
      name: caddy_net

services: 
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - 8096:8096
    volumes: 
      - ./config:/config
      - /mnt/extern:/mnt/extern 
    user: 1000:1000
    environment:
      - TZ=Europe/Stockholm
    group_add:  # grep -E 'render|video' /etc/group | cut -d: -f3
      - 44
      - 107
    devices:
      - /dev/dri/card0:/dev/dri/card0 
      - /dev/dri/renderD128:/dev/dri/renderD128
