version: "3" 

networks:
  default:
    external: 
      name: caddy_net

services: 
  jellyfin:
    image: jellyfin/jellyfin:10.6.4
    container_name: jellyfin
    restart: always
    ports:
        - 8096:8096
    volumes: 
        - ./config:/config
        - /mnt/extern:/mnt/extern 
    environment:
        - TZ=Europe/Stockholm
    # För att stödja hårdvaruomkodning (vaapi):
        - GIDLIST=44
    devices:
        - /dev/dri/renderD128:/dev/dri/renderD128
