# cant use mem_limit in a 3.x docker-compose file in non swarm mode
# see https://github.com/docker/compose/issues/4513
version: "2.4"

networks:
  default:
    external:
      name: caddy_net

services:
  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    hostname: whoogle
    restart: unless-stopped
    # pids_limit: 50
    # mem_limit: 256mb
    # memswap_limit: 256mb
    # user debian-tor from tor package
    user: '102'
    tmpfs:
      - /config/:size=10M,uid=102,gid=102,mode=1700
      - /var/lib/tor/:size=10M,uid=102,gid=102,mode=1700
      - /run/tor/:size=1M,uid=102,gid=102,mode=1700
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    # read_only: true
    environment: 
      - WHOOGLE_CONFIG_URL=$whoogle_config_url
      - WHOOGLE_CONFIG_COUNTRY_$whoogle_config_country
      - WHOOGLE_CONFIG_LANGUAGE=$whoogle_config_language
      # - WHOOGLE_CONFIG_STYLE=$whoogle_config_style
      # - WHOOGLE_CONFIG_DARK=1
      - WHOOGLE_CONFIG_GET_ONLY=1
      - WHOOGLE_CONFIG_VIEW_IMAGE=1
      - WHOOGLE_CONFIG_NEW_TAB=0
      - WHOOGLE_CONFIG_TOR=0
