version: "3.7"
services:

  adguard-home:
    image: "adguard/adguardhome"
    container_name: "adguard-home"
    hostname: "adguard-home"
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
    volumes:
      - ./work:/opt/adguardhome/work
      - ./config:/opt/adguardhome/config
# networks:
#   default:
#     external:
#       name: caddy_net
