version: "3"
services:

  adguard-home:
    image: "adguard/adguardhome"
    container_name: "adguard-home"
    hostname: "adguard-home"
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    environment:
      - TZ=Europe/Stockholm
# networks:
#   default:
#     external:
#       name: caddy_net
