version: "3"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - $tv:/tv
      - /home/antsva/docker/qbittorrent/downloads:/downloads
      - /home/antsva/bin:/usrbin:ro
    ports:
      - 8989:8989
