version: "3"

networks:
  default:
    external:
      name: caddy_net

services:
  nitter:
    image: zedeus/nitter:latest
    restart: unless-stopped
    container_name: nitter
    volumes:
      - ./nitter.conf:/src/nitter.conf
    depends_on:
      - nitter-db
    environment:
      - REDIS_HOST="nitter-db"

  nitter-db:
    image: redis:alpine
    container_name: nitter-db
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
