# .config/gebaar/gebaard.toml

[commands.swipe.three]
up = ""
down = ""
left = "xdotool key alt+Left"
right = "xdotool key alt+Right"

[commands.swipe.four]
up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Expose'"
down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Show Desktop'"
left = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Switch to Previous Desktop'"
right = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Switch to Next Desktop'"

[swipe.settings]
threshold = 0.5
one_shot = true
trigger_on_release = false
