version: "3"

networks:
  default:
    external:
      name: caddy_net

services:
  web:
    image: spikecodes/libreddit:latest
    restart: unless-stopped
    container_name: libreddit
    user: 1000:1000
    environment:
      LIBREDDIT_DEFAULT_COMMENT_SORT: "top"
      LIBREDDIT_SHOW_NSFW: "on"
