gapless = true

[keybindings]
"Space" = "playpause"
"Shift+p" = "queue"

[theme]
primary = "light white"
secondary = "light black"
title = "#4c566a"
playing = "green"
playing_selected = "light green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#4c566a"
# highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
