gapless = true
use_nerdfort = true

[keybindings]
"Space" = "playpause"
"Shift+p" = "queue"
"g" = "move top"
"G" = "move bottom"
"Ctrl+u" = "move up 5"
"Ctrl+d" = "move down 5"

[theme]
primary = "white"
secondary = "light black"
title = "blue"
# title = "#4c566a"
playing = "green"
playing_selected = "black"
playing_bg = "black"
highlight = "black"
# highlight_bg = "#4c566a"
highlight_bg = "green"
error = "white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "white"
cmdline_bg = "black"
search_match = "light red"
