version: "3"

services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - $movies:/movies
      - $tv:/tv
      - $documentaries:/documentaries
      - $manburst:/manburst
    ports:
      - 6767:6767
    restart: always
