version: "3"

services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - /mnt/extern/Media/Filmer/Övrigt:/movies
      - /mnt/extern/Media/Serier:/tv
      - /mnt/extern/Media/Dokumentärer:/documentaries
    ports:
      - 6767:6767
    restart: always
