version: '3' 

networks:
  default:
    external:
      name: caddy_net
  nextcloud-network:
    external: false

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - ./db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=$mysql_root_password
      - MYSQL_PASSWORD=$mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
    networks:
      - nextcloud-network

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud-network

  collabora:
    image: collabora/code:6.4.9.3
    container_name: collabora
    restart: unless-stopped
    environment:
      - DONT_GEN_SSL_CERT=1
      - domain=$collabora_domain
      - "dictionaries=en sv"
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    networks:
      - nextcloud-network
      - default
    depends_on:
      - db
      - redis
    volumes:
      - ./nextcloud:/var/www/html
      - ./config:/var/www/html/config
      - ./custom_apps:/var/www/html/custom_apps
      - ./data:/var/www/html/data
      - ./themes:/var/www/html/themes
    environment:
      - TZ=Europe/Stockholm
      - REDIS_HOST=nextcloud-redis
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=$mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS="$nextcloud_domain"
      - OVERWRITEHOST=$nextcloud_domain
      - OVERWRITEPROTOCOL=https
